export const RECIPE_CONFIG = [
    {
        id: '0',
        title: 'Картошка, тушенная с болгарским перцем и фасолью в томатном соусе',
        description:
            'Картошка, тушенная с болгарским перцем, фасолью, морковью и луком, - вариант сытного блюда на каждый день. Фасоль в данном случае заменяет мясо, делая рагу сытным и питательным. Чтобы сократить время приготовления, возьмём консервированную фасоль. Блюдо хоть и простое, но в полной мере наполнено ароматами и имеет выразительный вкус за счёт добавления томатной пасты.',
        category: ['vegan', 'second-dish'],
        subcategory: ['snacks', 'vegetables'],
        image: '/images/potato.svg',
        bookmarks: 85,
        likes: 152,
        date: '2025-02-28T00:00:00Z',
        time: '40 минут',
        portions: 2,
        nutritionValue: { calories: 250, proteins: 5, fats: 8, carbohydrates: 40 },
        ingredients: [
            { title: 'картошка', count: '4', measureUnit: 'шт.' },
            { title: 'болгарский перец', count: '2', measureUnit: 'шт.' },
            { title: 'фасоль', count: '200', measureUnit: 'г' },
            { title: 'томатный соус', count: '200', measureUnit: 'мл' },
            { title: 'лук', count: '1', measureUnit: 'шт.' },
            { title: 'специи', count: '0', measureUnit: 'по вкусу' },
        ],
        steps: [
            {
                stepNumber: 1,
                description: 'Нарезать картошку и перец.',
                image: '/images/step1.png',
            },
            {
                stepNumber: 2,
                description: 'Обжарить лук до золотистого цвета.',
                image: '/images/step2.png',
            },
            {
                stepNumber: 3,
                description: 'Добавить картошку, перец и фасоль, залить соусом.',
                image: null,
            },
            {
                stepNumber: 4,
                description: 'Тушить на медленном огне 30 минут.',
                image: '/images/step4.png',
            },
        ],
        meat: '',
        side: 'potatoes',
    },
    {
        id: '1',
        title: 'Картофельные рулетики с грибами',
        description:
            'Рекомендую всем приготовить постное блюдо из картофеля и грибов. Готовится это блюдо без яиц, без мяса и без сыра, из самых простых ингредиентов, а получается очень вкусно и сытно. Постный рецепт картофельных рулетиков с грибами, в томатном соусе, - на обед, ужин и даже на праздничный стол!',
        category: ['vegan', 'snacks'],
        subcategory: ['snacks', 'warm-snacks'],
        image: '/images/potatoWithMushrooms.svg',
        bookmarks: 85,
        likes: 1152,
        date: '2024-02-20T00:00:00Z',
        time: '30 минут',
        portions: 2,
        nutritionValue: { calories: 180, proteins: 4, fats: 6, carbohydrates: 28 },
        ingredients: [
            { title: 'картошка', count: '3', measureUnit: 'шт.' },
            { title: 'грибы', count: '200', measureUnit: 'г' },
            { title: 'мука', count: '100', measureUnit: 'г' },
            { title: 'специи', count: '0', measureUnit: 'по вкусу' },
        ],
        steps: [
            {
                stepNumber: 1,
                description: 'Отварить картошку и сделать пюре.',
                image: '/images/step1.png',
            },
            {
                stepNumber: 2,
                description: 'Обжарить грибы до готовности.',
                image: null,
            },
            {
                stepNumber: 3,
                description: 'Сформировать рулетики и обжарить.',
                image: '/images/step3.png',
            },
        ],
        side: 'potatoes',
    },
    {
        id: '2',
        title: 'Овощная лазанья из лаваша',
        description:
            'Большое, сытное блюдо для ценителей блюд без мяса! Такая лазанья готовится с овощным соусом и соусом бешамель, а вместо листов для лазаньи используется тонкий лаваш.',
        category: ['vegan', 'second-dish', 'national'],
        subcategory: ['second-dish', 'vegetables', 'italian', 'snacks'],
        image: '/images/vegetableAzania.svg',
        bookmarks: 85,
        likes: 152,
        date: '2023-01-25T00:00:00Z',
        time: '1 час',
        portions: 1,
        nutritionValue: { calories: 300, proteins: 12, fats: 8, carbohydrates: 45 },
        ingredients: [
            { title: 'лаваш', count: '3', measureUnit: 'листов' },
            { title: 'овощной соус', count: '300', measureUnit: 'мл' },
            { title: 'соус бешамель', count: '200', measureUnit: 'мл' },
            { title: 'сыр', count: '100', measureUnit: 'г' },
        ],
        steps: [
            { stepNumber: 1, description: 'Приготовить соусы.', image: '/images/step1.png' },
            { stepNumber: 2, description: 'Сложить слои лазаньи.', image: null },
            { stepNumber: 3, description: 'Запекать 30 минут.', image: '/images/step3.png' },
        ],
    },
    {
        id: '3',
        title: 'Тефтели из булгура и чечевицы, запечённые в томатном соусе',
        description:
            'Тефтели из булгура и чечевицы – яркие и питательные, отлично подходят для постного и вегетарианского меню. Тефтели получаются нежными, а также сочными и ароматными благодаря использованию томатного соуса и душистых пряностей.',
        category: ['vegan', 'second-dish'],
        subcategory: ['second-dish', 'poultry-dish'],
        image: '/images/meatballs.svg',
        bookmarks: 85,
        likes: 152,
        date: '2023-02-15T00:00:00Z',
        time: '50 минут',
        portions: 4,
        nutritionValue: { calories: 200, proteins: 10, fats: 5, carbohydrates: 30 },
        ingredients: [
            { title: 'булгур', count: '150', measureUnit: 'г' },
            { title: 'чечевица', count: '100', measureUnit: 'г' },
            { title: 'томатный соус', count: '200', measureUnit: 'мл' },
            { title: 'лук', count: '1', measureUnit: 'шт.' },
        ],
        steps: [
            {
                stepNumber: 1,
                description: 'Смешать булгур и чечевицу.',
                image: '/images/step1.png',
            },
            {
                stepNumber: 2,
                description: 'Сформировать тефтели и запечь.',
                image: '/images/step2.png',
            },
            { stepNumber: 3, description: 'Подавать с соусом.', image: null },
        ],
    },
    {
        id: '4',
        title: 'Чесночная картошка',
        description:
            'Такая картошечка украсит любой семейный обед! Все будут в полном восторге, очень вкусно! Аромат чеснока, хрустящая корочка на картошечке - просто объедение! Отличная идея для обеда или ужина, готовится просто!',
        category: ['vegan', 'second-dish'],
        subcategory: ['side-dishes', 'second-dish', 'vegetables'],
        image: '/images/garlicPotato.svg',
        bookmarks: 124,
        likes: 342,
        date: '2024-03-01T00:00:00Z',
        time: '30 минут',
        portions: 2,
        nutritionValue: { calories: 220, proteins: 4, fats: 7, carbohydrates: 35 },
        ingredients: [
            { title: 'картошка', count: '6', measureUnit: 'шт.' },
            { title: 'чеснок', count: '5', measureUnit: 'зубчиков' },
            { title: 'масло', count: '50', measureUnit: 'мл' },
            { title: 'специи', count: '0', measureUnit: 'по вкусу' },
        ],
        steps: [
            {
                stepNumber: 1,
                description: 'Очистить и нарезать картошку.',
                image: '/images/step1.png',
            },
            { stepNumber: 2, description: 'Обжарить с чесноком.', image: '/images/step2.png' },
            { stepNumber: 3, description: 'Подавать горячей.', image: '/images/step3.png' },
        ],
        side: 'potatoes',
    },

    {
        id: '5',
        title: 'Фаршированные шампиньоны в духовке',
        description:
            'Фаршированные шампиньоны – это сытная закуска, подходящая как для повседневного меню, так и для праздничного стола. Начинка может быть разной – от овощей до круп или сыра. Здесь использован базовый рецепт с овощной начинкой.',
        category: ['vegan', 'snacks'],
        subcategory: ['warm-snacks', 'vegetables'],
        image: '/images/potatoWithMushrooms.svg',
        bookmarks: 78,
        likes: 198,
        date: '2024-03-12T00:00:00Z',
        time: '35 минут',
        portions: 2,
        nutritionValue: { calories: 160, proteins: 6, fats: 5, carbohydrates: 20 },
        ingredients: [
            { title: 'шампиньоны', count: '10', measureUnit: 'шт.' },
            { title: 'морковь', count: '1', measureUnit: 'шт.' },
            { title: 'лук', count: '1', measureUnit: 'шт.' },
            { title: 'растительное масло', count: '30', measureUnit: 'мл' },
        ],
        steps: [
            {
                stepNumber: 1,
                description: 'Подготовить грибы, удалить ножки.',
                image: '/images/step1.png',
            },
            {
                stepNumber: 2,
                description: 'Приготовить начинку из овощей.',
                image: '/images/step2.png',
            },
            {
                stepNumber: 3,
                description: 'Фаршировать и запечь в духовке.',
                image: null,
            },
        ],
    },
    {
        id: '6',
        title: 'Запечённые баклажаны с томатами и чесноком',
        description:
            'Это блюдо покорит вас своей простотой и насыщенным вкусом! Сочетание баклажанов, томатов и чеснока – классика средиземноморской кухни. Отличная идея для лёгкого ужина.',
        category: ['vegan', 'second-dish'],
        subcategory: ['second-dish', 'vegetables', 'side-dishes'],
        image: '/images/garlicPotato.svg',
        bookmarks: 64,
        likes: 143,
        date: '2024-04-01T00:00:00Z',
        time: '45 минут',
        portions: 2,
        nutritionValue: { calories: 180, proteins: 3, fats: 9, carbohydrates: 20 },
        ingredients: [
            { title: 'баклажаны', count: '2', measureUnit: 'шт.' },
            { title: 'помидоры', count: '3', measureUnit: 'шт.' },
            { title: 'чеснок', count: '4', measureUnit: 'зубчика' },
            { title: 'растительное масло', count: '40', measureUnit: 'мл' },
        ],
        steps: [
            {
                stepNumber: 1,
                description: 'Нарезать баклажаны и помидоры.',
                image: '/images/step1.png',
            },
            {
                stepNumber: 2,
                description: 'Выложить слоями с чесноком и маслом.',
                image: '/images/step2.png',
            },
            {
                stepNumber: 3,
                description: 'Запечь в духовке 30 минут.',
                image: '/images/step3.png',
            },
        ],
    },
    {
        id: '7',
        title: 'Постные голубцы с рисом и грибами',
        description:
            'Постные голубцы – отличная альтернатива мясным. Рис и грибы создают сытную и ароматную начинку, а капустные листья сохраняют сочность.',
        category: ['vegan', 'second-dish'],
        subcategory: ['second-dish', 'vegetables', 'warm-snacks'],
        image: '/images/garlicPotato.svg',
        bookmarks: 101,
        likes: 254,
        date: '2024-05-15T00:00:00Z',
        time: '1 час',
        portions: 4,
        nutritionValue: { calories: 190, proteins: 5, fats: 4, carbohydrates: 30 },
        ingredients: [
            { title: 'капуста', count: '1', measureUnit: 'кочан' },
            { title: 'рис', count: '100', measureUnit: 'г' },
            { title: 'грибы', count: '150', measureUnit: 'г' },
            { title: 'лук', count: '1', measureUnit: 'шт.' },
        ],
        steps: [
            { stepNumber: 1, description: 'Отварить листья капусты.', image: '/images/step1.png' },
            {
                stepNumber: 2,
                description: 'Приготовить начинку из риса и грибов.',
                image: '/images/step2.png',
            },
            {
                stepNumber: 3,
                description: 'Сформировать голубцы и тушить в соусе.',
                image: '/images/step3.png',
            },
        ],
    },
    {
        id: '8',
        title: 'Кабачковые оладьи',
        description:
            'Кабачковые оладьи – быстрый и вкусный способ разнообразить меню. Они получаются нежными, ароматными и идеально сочетаются со сметаной или соусом.',
        category: ['vegan', 'snacks'],
        subcategory: ['warm-snacks', 'vegetables'],
        image: '/images/garlicPotato.svg',
        bookmarks: 75,
        likes: 210,
        date: '2024-06-05T00:00:00Z',
        time: '20 минут',
        portions: 3,
        nutritionValue: { calories: 140, proteins: 3, fats: 5, carbohydrates: 18 },
        ingredients: [
            { title: 'кабачки', count: '2', measureUnit: 'шт.' },
            { title: 'мука', count: '100', measureUnit: 'г' },
            { title: 'соль', count: '0', measureUnit: 'по вкусу' },
            { title: 'масло для жарки', count: '30', measureUnit: 'мл' },
        ],
        steps: [
            {
                stepNumber: 1,
                description: 'Натереть кабачки и отжать сок.',
                image: '/images/step1.png',
            },
            {
                stepNumber: 2,
                description: 'Смешать с мукой и специями.',
                image: '/images/step2.png',
            },
            {
                stepNumber: 3,
                description: 'Обжарить до золотистой корочки.',
                image: '/images/step3.png',
            },
        ],
    },
];
